export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGIN_LOADING = 'LOGIN_LOADING';

export const GET_MESSAGES_FAILED = 'GET_MESSAGES_FAILED';
export const GET_MESSAGES_SUCCESSFUL = 'GET_MESSAGES_SUCCESSFUL';
export const GET_MESSAGES_LOADING = 'GET_MESSAGES_LOADING';

export const ADD_NEW_MESSAGE_FAILED = 'ADD_NEW_MESSAGE_FAILED';
export const ADD_NEW_MESSAGE_SUCCESSFUL = 'ADD_NEW_MESSAGE_SUCCESSFUL';
export const ADD_NEW_MESSAGE_LOADING = 'ADD_NEW_MESSAGE_LOADING';
